# Site settings
title: nullday
email: chris@nullday.de
description: "nullday ist der private webspace von Christian Rebischke. Letzte Veränderung: 2018-10-01"
baseurl: ""
url: "https://www.nullday.de"
twitter_username: sh1bumi
github_username:  shibumi
linkedin_username: shibumi
google_plus_username: ChristianRebischke
xing_username: Christian_Rebischke

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
