# Site settings
title: nullday
email: chris@nullday.de
description: "nullday ist der private webspace von Christian Rebischke und powered by jekyll: Garantiert ohne Javascript, PHP, Cookies und MySQL. Letzte Veränderung: 16.7.2016"
baseurl: ""
url: "http://www.nullday.de"
twitter_username: sh1bumi
github_username:  shibumi
linkedin_username: shibumi

# Build settings
markdown: rdiscount
permalink: pretty
highlighter: pygments
