apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nullday
  namespace: nullday
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nullday.de
    spec:
      containers:
      - name: nullday
        image: sh1bumi/nullday.de:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
